### ISSUE TITLE
Readme run instructions don't work, assumes higher level directory

### ISSUE THREAD

**Issue by Evan-Kim2028** [OffchainLabs/Blobwatcher#2]
`go run ./.. -- --execution-endpoint ws://localhost:8546 --metrics-endpoint localhost:8080` <- doesn't work. Directory issues.

`go run .--execution-endpoint ws://localhost:8546 --metrics-endpoint localhost:8080` <- This works when run in the directory

**Comment by nisdas** [comment]
Thanks for the report ! #3 should fix it
